In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model, metrics

# Multivariate Linear Regression

In [3]:
df=pd.read_csv("train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

Identifikasi Variabel

- MSSubClass: The building class
- MSZoning: The general zoning classification
- LotFrontage: Linear feet of street connected to property
- LotArea: Lot size in square feet
- Street: Type of road access
- Alley: Type of alley access
- LotShape: General shape of property
- LandContour: Flatness of the property
- Utilities: Type of utilities available
- LotConfig: Lot configuration
- LandSlope: Slope of property
- Neighborhood: Physical locations within Ames city limits
- Condition1: Proximity to main road or railroad
- Condition2: Proximity to main road or railroad (if a second is present)
- BldgType: Type of dwelling
- HouseStyle: Style of dwelling
- OverallQual: Overall material and finish quality
- OverallCond: Overall condition rating
- YearBuilt: Original construction date
- YearRemodAdd: Remodel date
- RoofStyle: Type of roof
- RoofMatl: Roof material
- Exterior1st: Exterior covering on house
- Exterior2nd: Exterior covering on house (if more than one material)
- MasVnrType: Masonry veneer type
- MasVnrArea: Masonry veneer area in square feet
- ExterQual: Exterior material quality
- ExterCond: Present condition of the material on the exterior
- Foundation: Type of foundation
- BsmtQual: Height of the basement
- BsmtCond: General condition of the basement
- BsmtExposure: Walkout or garden level basement walls
- BsmtFinType1: Quality of basement finished area
- BsmtFinSF1: Type 1 finished square feet
- BsmtFinType2: Quality of second finished area (if present)
- BsmtFinSF2: Type 2 finished square feet
- BsmtUnfSF: Unfinished square feet of basement area
- TotalBsmtSF: Total square feet of basement area
- Heating: Type of heating
- HeatingQC: Heating quality and condition
- CentralAir: Central air conditioning
- Electrical: Electrical system
- 1stFlrSF: First Floor square feet
- 2ndFlrSF: Second floor square feet
- LowQualFinSF: Low quality finished square feet (all floors)
- GrLivArea: Above grade (ground) living area square feet
- BsmtFullBath: Basement full bathrooms
- BsmtHalfBath: Basement half bathrooms
- FullBath: Full bathrooms above grade
- HalfBath: Half baths above grade
- Bedroom: Number of bedrooms above basement level
- Kitchen: Number of kitchens
- KitchenQual: Kitchen quality
- TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
- Functional: Home functionality rating
- Fireplaces: Number of fireplaces
- FireplaceQu: Fireplace quality
- GarageType: Garage location
- GarageYrBlt: Year garage was built
- GarageFinish: Interior finish of the garage
- GarageCars: Size of garage in car capacity
- GarageArea: Size of garage in square feet
- GarageQual: Garage quality
- GarageCond: Garage condition
- PavedDrive: Paved driveway
- WoodDeckSF: Wood deck area in square feet
- OpenPorchSF: Open porch area in square feet
- EnclosedPorch: Enclosed porch area in square feet
- 3SsnPorch: Three season porch area in square feet
- ScreenPorch: Screen porch area in square feet
- PoolArea: Pool area in square feet
- PoolQC: Pool quality
- Fence: Fence quality
- MiscFeature: Miscellaneous feature not covered in other categories
- MiscVal: $Value of miscellaneous feature
- MoSold: Month Sold
- YrSold: Year Sold
- SaleType: Type of sale
- SaleCondition: Condition of sale
- SalePrice - the property's sale price in dollars. This is the target variable that you're trying to predict

**One Hot Encoding, Fill NA**

Drop variabel id dan drop variabel yang diasumsuikan memiliki missing value banyak

In [5]:
df.drop(labels=['Id','Alley','PoolQC','Fence','MiscFeature'],axis=1,inplace=True)

Mengisi NA (Fill NA)

In [6]:
df['LotFrontage']=df['LotFrontage'].fillna(df['LotFrontage'].mean())
df['MasVnrType']=df['MasVnrType'].fillna(df['MasVnrType'].mode()[0])
df['MasVnrArea']=df['MasVnrArea'].fillna(df['MasVnrArea'].mode()[0])
df['BsmtQual']=df['BsmtQual'].fillna(df['BsmtQual'].mode()[0])
df['BsmtCond']=df['BsmtCond'].fillna(df['BsmtCond'].mode()[0])
df['BsmtExposure']=df['BsmtExposure'].fillna(df['BsmtExposure'].mode()[0])
df['BsmtFinType1']=df['BsmtFinType2'].fillna(df['BsmtFinType1'].mode()[0])
df['BsmtFinType2']=df['BsmtFinType2'].fillna(df['BsmtFinType2'].mode()[0])
df['Electrical']=df['Electrical'].fillna(df['Electrical'].mode()[0])
df['FireplaceQu']=df['FireplaceQu'].fillna(df['FireplaceQu'].mode()[0])
df['GarageType']=df['GarageType'].fillna(df['GarageType'].mode()[0])
df['GarageYrBlt']=df['GarageYrBlt'].fillna(df['GarageYrBlt'].mode()[0])
df['GarageFinish']=df['GarageFinish'].fillna(df['GarageFinish'].mode()[0])
df['GarageQual']=df['GarageQual'].fillna(df['GarageQual'].mode()[0])
df['GarageCond']=df['GarageCond'].fillna(df['GarageCond'].mode()[0])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  MasVnrType     1460 non-null   object
 24  MasVnrArea     1460 non-null   float64
 25  ExterQual      1460 non-null   object
 26  ExterCond      1460 non-null   object
 27  Foundation     1460 non-null   object
 28  BsmtQual       1460 non-null   object
 29  BsmtCond       1460 non-null   object
 30  BsmtExposure   1460 non-null   object
 31  BsmtFinType1   1460 non-null   object
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1460 non-null   object
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   object
 38  HeatingQC      1460 non-null   object
 39  CentralAir     1460 non-null   object
 40  Electrical     1460 non-null   object
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   object
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   object
 54  Fireplaces     1460 non-null   int64
 55  FireplaceQu    1460 non-null   object
 56  GarageType     1460 non-null   object
 57  GarageYrBlt    1460 non-null   float64
 58  GarageFinish   1460 non-null   object
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1460 non-null   object
 62  GarageCond     1460 non-null   object
 63  PavedDrive     1460 non-null   object
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  MiscVal        1460 non-null   int64
 71  MoSold         1460 non-null   int64
 72  YrSold         1460 non-null   int64
 73  SaleType       1460 non-null   object
 74  SaleCondition  1460 non-null   object
 75  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(39)
memory usage: 867.0+ KB

**One Hot Encoding**

In [8]:
dfcode = pd.get_dummies(df)
dfcode.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0

In [9]:
dfcode.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 276 entries, MSSubClass to SaleCondition_Partial
dtypes: float64(3), int64(34), uint8(239)
memory usage: 762.9 KB

Mendefinisikan variabel x dan y

In [10]:
x = dfcode.loc[:, dfcode.columns != 'SalePrice']
y = dfcode["SalePrice"]

In [11]:
x

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,0,1,0

**Separate into X_train, X_test, y_train, y_test (y = “SalePrice”) with proportion: 60-40**

In [12]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=1)

**Train regression model with X_train and y_train**

In [13]:
# create linear regression object
reg = linear_model.LinearRegression()
 
# train the model using the training sets
reg.fit(x_train, y_train)
 
# regression coefficients
print('Coefficients: ', reg.coef_)

# regression intercept
print('Intercept: ', reg.intercept_)

Coefficients:  [-1.64986710e+02  5.50663093e+01  1.07844014e+00  5.44865580e+03
  5.88995083e+03  2.58164179e+02  2.74317630e+01  1.37744175e+01
  1.87758101e+01 -2.84183948e+00 -1.13438967e+00  1.47995797e+01
  1.81535065e+01  2.71521803e+01 -6.51408780e+00  3.87915989e+01
  3.13487179e+02  1.96730074e+03  3.43017459e+03  1.77626474e+03
 -2.47360319e+03 -1.16335540e+04 -1.26983631e+02  2.41847956e+03
  3.33296112e+01  4.07290821e+03  1.50146435e+01  7.99099439e+00
  2.41063321e+01 -2.23824438e+00  1.79084784e+01  1.75574209e+01
  3.51081678e+01  6.15205777e-01 -3.11413322e+02 -4.57334073e+02
 -3.59737142e+04  1.63860586e+04  1.75962401e+04  8.73145430e+02
  1.11827003e+03  2.71001806e+03 -2.71001806e+03  1.75430836e+03
  1.11526955e+02 -4.62105419e+03  2.75521888e+03 -3.11917379e+02
  1.06082341e+04 -1.53488992e+04  5.05258252e+03  2.27830474e+04
 -2.27830474e+04  1.64405371e+03  6.96082823e+03 -7.33291825e+02
 -6.57911678e+03 -1.29247334e+03  2.48984374e+04  2.65678453e+04
 -5.14662827e+04  1.81323413e+04  5.36442014e+03  8.11625583e+03
 -6.06502316e+03 -8.80378136e+03 -4.69876393e+03  1.86524604e+04
 -1.60658679e+04 -1.26545568e+04 -1.09842193e+04  4.43242103e+03
 -1.50412412e+04 -1.66397971e+04  1.88783553e+04 -1.37543028e+04
  2.16538562e+04  1.27264648e+04 -1.37701263e+04 -1.23319450e+04
 -9.76646539e+03 -3.14447294e+02 -9.98871836e+03  5.90827905e+04
 -6.93443717e+03 -9.22567252e+03 -5.99209900e+03 -3.80116433e+03
  9.79665195e+03 -5.56314374e+03  6.00132513e+03 -1.83406513e+04
  1.65861556e+04  4.93601564e+03 -3.62308991e+03  9.04093267e+04
  5.33711741e+04  7.09563612e+04  7.89244767e+04 -3.89083627e+05
  1.39099355e+04  5.09317033e-11  8.15123525e+04  2.16839894e+03
  8.78669721e+03 -2.15612062e+03 -6.19055475e+03 -2.60842078e+03
  4.75751217e+02  1.02820555e+04 -5.96975946e+02 -2.69278010e+04
  5.60622962e+03 -3.88481252e+03  6.51525618e+03  8.53029689e+03
 -7.08682930e+03 -8.45692310e+03  1.34875793e+01 -6.94591941e+03
  8.56624872e+03  1.39099355e+04 -2.47382559e-10 -2.34355767e+04
  1.02880054e+05 -3.20142135e-10 -4.37471941e+04 -2.80976595e+04
 -4.98777821e+04  4.22781584e+04  1.47511803e+04 -4.91127139e-11
 -1.43369093e+04  1.47033546e+04 -1.74622983e-10 -1.50994810e+04
 -1.92136753e+03 -8.46680969e+03  3.47999232e+03 -1.28013063e+03
  1.87486199e+04 -4.75962573e+03  3.04375235e+03 -6.30476321e+03
 -2.55781228e+03 -6.16692028e+03 -3.40701963e+03  8.78070894e+02
 -3.01256497e+03  1.07775122e-10  2.15476025e+04  3.82884778e+03
  4.26782810e+03  4.76581549e+03 -3.88184450e+04  1.23814264e+03
 -2.01793444e+04  1.03716171e+04  5.36336933e+03  1.21999793e+04
  7.12302114e+03 -9.76423096e+03 -1.22174989e+03  9.86154479e+02
  9.99982638e+03  3.09805669e+04 -4.90618598e+03 -1.25018146e+04
 -1.35725664e+04  1.94893083e+02  4.74611019e+03 -4.03456396e+03
 -4.54747351e-11 -9.06439312e+02 -4.05017033e+03  2.07481973e+03
  5.05744717e+03 -1.04590777e+03  2.08542170e+04 -2.28904058e+04
  9.04290093e+03 -5.63936879e+03 -4.71247051e+03  1.30893837e+03
 -7.43723293e+03 -7.25519155e+03  1.68823486e+04 -2.18992417e+03
 -3.10932835e+03  1.65922257e+04 -6.52849649e+03 -6.95440083e+03
  7.32714324e+03 -2.13581811e+03 -5.96662669e+01 -3.60002917e+03
  5.98118096e+02 -2.12974779e+03  7.32714324e+03 -2.13581811e+03
 -5.96662669e+01 -3.60002917e+03  5.98118096e+02 -2.12974779e+03
  2.80151850e+03  4.53329696e+03 -8.31070193e+03 -1.09694842e+02
 -2.93252838e+04  3.04108651e+04  2.82535150e+03 -1.70352596e+03
  3.01930234e+02 -1.81898940e-12 -1.42375577e+03  2.70290398e+03
 -2.70290398e+03 -1.94531795e+03 -1.45791189e+03 -9.14308918e+03
  1.68823486e+04 -4.33602962e+03  1.88783358e+04 -3.69186665e+03
 -7.29619825e+03 -7.89027086e+03  8.34622473e+03  3.89450273e+03
  9.22873066e+03  1.35679363e+04 -1.85539373e+03 -5.42711687e+04
  2.10891681e+04 -7.79706589e+03 -2.58200565e+03  1.02413415e+02
  1.02740394e+04  2.61875792e+00 -1.41236728e+04 -9.08778794e+02
 -2.16590233e+02  4.92986039e+03  8.84499643e+03  1.47418498e+03
 -1.81875705e+03  3.93258779e+02  1.42549827e+03  8.68105140e+04
 -1.27038470e+04 -1.32931523e+04 -5.14936348e+04 -9.31987993e+03
 -7.89507635e+04  1.60807613e+04  1.90652942e+04  2.94968716e+04
  1.43078364e+04  3.35349572e+03 -5.63729615e+03  2.28380043e+03
 -8.58620026e+03 -1.19483166e+04  3.46033392e+04 -2.18119318e+03
 -1.41513036e+04 -1.40003708e+04  9.40126122e+03  1.83938938e+04
 -1.15311097e+04 -1.12860746e+04 -6.57309483e+02  1.74534247e+04
 -1.47164866e+03  6.94798219e+02 -4.73319014e+03]
Intercept:  190455.3131580964

**Evaluate the result with 3 metrics**

In [14]:
y_pred = reg.predict(x_test)

In [15]:
# MAE
from sklearn.metrics import mean_absolute_error
print("MAE :",mean_absolute_error(y_test, y_pred))
# MSE
from sklearn.metrics import mean_squared_error
print("MSE :",mean_squared_error(y_test, y_pred))
# RMSE
from sklearn.metrics import mean_squared_error
print("RMSE :",np.sqrt(mean_squared_error(y_test,y_pred)))
# R2
from sklearn.metrics import r2_score
print("R2 :",r2_score(y_test, y_pred))

MAE : 20059.753489620478
MSE : 1880576394.785678
RMSE : 43365.61304519605
R2 : 0.7154770487589648

**Explain or Interpret the linear correlation between 3 features and the target (“SalePrice”)**

Interpretasi :
- MAE : rata-rata kesalahan absolut antara nilai yang sebenarnya dan nilai prediksi sebesar 20059.753489620478
- RMSE: jumlah dari kesalahan kuadrat atau selisih antara nilai sebenarnya dengan nilai prediksi sebesar 43365.61304519605
- R2 : akurasi model regresi sebesar 71.55%. Dimana 71.55% variasi dari variabel dependen SalePrice (Y) dapat dijelaskan oleh variabel independen (X). Sedangkan sisanya 28.45% dapat dijelaskan oleh variabel lain yang tidak terdapat dalam model.

# Classification Model

In [16]:
df2=pd.read_csv("heart.csv")
df2

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [18]:
df2.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

### One Hot Encoding

In [19]:
df2code = pd.get_dummies(df2)
df2code

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0.0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [20]:
df2code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   RestingBP          918 non-null    int64
 2   Cholesterol        918 non-null    int64
 3   FastingBS          918 non-null    int64
 4   MaxHR              918 non-null    int64
 5   Oldpeak            918 non-null    float64
 6   HeartDisease       918 non-null    int64
 7   Sex_F              918 non-null    uint8
 8   Sex_M              918 non-null    uint8
 9   ChestPainType_ASY  918 non-null    uint8
 10  ChestPainType_ATA  918 non-null    uint8
 11  ChestPainType_NAP  918 non-null    uint8
 12  ChestPainType_TA   918 non-null    uint8
 13  RestingECG_LVH     918 non-null    uint8
 14  RestingECG_Normal  918 non-null    uint8
 15  RestingECG_ST      918 non-null    uint8
 16  ExerciseAngina_N   918 non-null    uint8
 17  ExerciseAngina_Y   918 non-null    uint8
 18  ST_Slope_Down      918 non-null    uint8
 19  ST_Slope_Flat      918 non-null    uint8
 20  ST_Slope_Up        918 non-null    uint8
dtypes: float64(1), int64(6), uint8(14)
memory usage: 62.9 KB

Mendefinisikan variabel x dan y

In [21]:
# defining feature matrix(X) and response vector(y)
x = df2code.loc[:, df2code.columns != 'HeartDisease']
y = df2code["HeartDisease"]

### Separate into X_train, X_test, y_train, y_test (y = “HeartDisease”) with proportion: 60-40

In [22]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=1)

### Train two models with X_train and y_train (use Hyperparameter Tuning for random forest)

#### Logistic Regression

In [23]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1500)
lr = lr.fit(x_train, y_train)

#### Random Forest

In [24]:
## Random Forest
from sklearn.ensemble import RandomForestClassifier

classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)

classifier_rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [25]:
#Hyperparameter Tuning for random forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42, n_jobs=-1)

params = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}

In [26]:
from sklearn.model_selection import GridSearchCV

#Instantiate the grid search model
grid_search = GridSearchCV(estimator=rf,
                           param_grid=params,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")

grid_search.fit(x_train, y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [27]:
grid_search.best_score_

0.8708611022955675

In [28]:
rf_best = grid_search.best_estimator_
rf_best.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=5, n_estimators=50,
                       n_jobs=-1, random_state=42)

### Evaluate the result with confusion matrix, classification report, and AUC

In [29]:
y_lr = lr.predict(x_test)        
y_rf = rf_best.predict(x_test)

**Confusion Matrix**

In [30]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_lr))
print(confusion_matrix(y_test, y_rf))

[[133  20]
 [ 29 186]]
[[127  26]
 [ 20 195]]

In [31]:
#Accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_lr))
print(accuracy_score(y_test, y_rf))

0.8668478260869565
0.875

Berdasarkan akurasi dari confusion matrix, model yang paling baik menggunakan random forest. Sebab, angka akurasi random forest lebih tinggi.

**Classification Report**

In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_lr))
print(classification_report(y_test, y_rf))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84       153
           1       0.90      0.87      0.88       215

    accuracy                           0.87       368
   macro avg       0.86      0.87      0.86       368
weighted avg       0.87      0.87      0.87       368

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       153
           1       0.88      0.91      0.89       215

    accuracy                           0.88       368
   macro avg       0.87      0.87      0.87       368
weighted avg       0.87      0.88      0.87       368

Berdasarkan Classification Report, model yang paling baik menggunakan random forest  daripada linear regression.

**AUC**

In [33]:
from sklearn.metrics import roc_curve, auc
fpr, tpr, thresholds = roc_curve(y_test, y_lr, pos_label=1) # pos_label: positive label
print(auc(fpr, tpr))
fpr, tpr, thresholds = roc_curve(y_test, y_rf, pos_label=1) # pos_label: positive label
print(auc(fpr, tpr))

0.8671986624107006
0.8685210518315852

Berdasarkan AUC, model yang paling baik menggunakan random forest daripada linear regression.

**Comparison Better Model
Which model is better at predicting Heart Disease? Interpret the reason.**

Berdasarkan hasil evaluasi dari 2 model dengan menggunakan confusion matrix, classification report, dan AUC. Didapatkan hasil bahwa dari ketiganya menunjukkan bahwa model yang lebih baik adalah random forest. Jadi, dapat disimpulkan bahwa model random forest lebih baik dalam memprediksi Heart Disease atau Penyakit Jantung.